---
name: Receiver

on:
  workflow_run:
    workflows: [Sender]
    types:
      - completed

jobs:
  Receive:
    runs-on: ubuntu-latest

    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "run_number"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/run_number.zip`, Buffer.from(download.data));

      - name: 'Unzip artifact'
        run: unzip run_number.zip

      - name: 'Save run number to output'
        id: save_run_number
        # run: cat ./run_number
        run: echo "::set-output name=run_number::$(cat ./run_number)"

      - name: 'Log output'
        # run: cat ./run_number
        run: echo ${{steps.save_run_number.outputs.run_number}}
# 